apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodCatalog
  labels:
    app: foodCatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodCatalog
  template:
    metadata:
      labels:
        app: foodCatalog
    spec:
      containers:
        - name: foodCatalog
          image: hscrg.azurecr.io/foodCatalog:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5